### ISSUE TITLE
Can't use custom templates for receivers

### ISSUE THREAD

**Issue by wikro** [cloudalchemy/ansible-alertmanager#119]
I tried adding custom templates, using `alertmanager_template_files`, which works. What doesn't work is when I configure the receiver:

```yaml
alertmanager_receivers:
  - name: "receiver"
    pagerduty_configs:
      - routing_key: "xxx"
        send_resolved: true
        description: '{{ template "pagerduty.custom.description" . }}'
``` 

The job failes on preflight.yml, `Fail when there are no receivers defined` and Ansible says

```
Error was a <class 'ansible.errors.AnsibleError'>, original message: template error while templating string: expected token 'end of print statement', got 'string'. String: {{ template \"pagerduty.custom.description\" . }}
```

What am I expected to write to use custom templates?
