### ISSUE TITLE
Support for webhook_config

### ISSUE THREAD

**Issue by IDerr** [cloudalchemy/ansible-alertmanager#127]
Hello, 
from what I have seen, this ansible role doesn't support the webhook config field in the alertmanager.yml.
https://prometheus.io/docs/alerting/configuration/#webhook_config

Will you support it in the near future ?
Thanks a lot for your work !

**Comment by paulfantom** [comment]
Every receiver defined by alertmanager is supported as this role is defining `alertmanager_receivers` and passing its content to `receivers` field in alertmanager config. Which means following config is responsible for webhook_receiver:
```
alertmanager_receivers:
  - name: slack
    webhook_configs:
      - send_resolved: true
        url: "https://example.org"
```
