### ISSUE TITLE
Add on README.md example playbook that alertmanager_route and alertmanager_receivers is needed

### ISSUE THREAD

**Issue by bryanasdev000** [cloudalchemy/ansible-alertmanager#132]
**What is missing?**

Add on README.md a example playbook that `alertmanager_route` and `alertmanager_receivers` is needed to the role to achieve the desired state.

Even if it is in the documentation of the variables, it does not explain the obligation of the same and as the demonstration project is archived, I find it interesting to provide a basic example (functional or not) with these two variables.

**Why do we need it?**

Quickstart for anyone that want to use this excellent role.

**Environment**

* Role version:

    `3f4f089cae9fb6cf7a71c27745a3a5e6eac0b929`

* Ansible version information:

    `ansible --version`
    

**Anything else we need to know?**:

If desired I can perform a PR with the content below (simple boilerplate for Telegram) that I am using in another repository for example:
```yaml
- name: AlertManager role
  hosts: monitoring
  become: yes
  roles:
    - role: cloudalchemy.alertmanager
      vars:
        alertmanager_route:
          group_by: [job]
          receiver: default
        alertmanager_receivers:
          - name: default
            webhook_configs:
            - send_resolved: True
              url: http://localhost:9087/alert/-chatid
```

Thanks for the excellent role!
