### ISSUE TITLE
slack template issue

### ISSUE THREAD

**Issue by inkdude** [cloudalchemy/ansible-alertmanager#140]
**What did you do?**
I want to setup template notifications in slack
**Did you expect to see some different?**
-
**Environment**
-
* Role version:
latest
    `Insert release version/galaxy tag or Git SHA here`
https://galaxy.ansible.com/cloudalchemy/alertmanager (i can't find galaxy tag or something)
* Ansible version information:

    `ansible --version`
    ansible 2.9.6

* Variables:

```
---
alertmanager_version: latest
alertmanager_binary_local_dir: ''

alertmanager_config_dir: /etc/alertmanager
alertmanager_db_dir: /var/lib/alertmanager

alertmanager_config_file: 'alertmanager.yml.j2'

alertmanager_template_files:
  - templates/*.tmpl

alertmanager_web_listen_address: '0.0.0.0:9093'
alertmanager_web_external_url: 'http://localhost:9093/'

alertmanager_http_config: {}

alertmanager_resolve_timeout: 3m

alertmanager_config_flags_extra: {}
# alertmanager_config_flags_extra:
#   data.retention: 10

# SMTP default params
alertmanager_smtp: {}
# alertmanager_smtp:
#   from: ''
#   smarthost: ''
#   auth_username: ''
#   auth_password: ''
#   auth_secret: ''
#   auth_identity: ''
#   require_tls: "True"

# Default values you can see here -> https://prometheus.io/docs/alerting/configuration/
alertmanager_slack_api_url: 'XXX'
alertmanager_pagerduty_url: ''
alertmanager_opsgenie_api_key: ''
alertmanager_opsgenie_api_url: ''
alertmanager_victorops_api_key: ''
alertmanager_victorops_api_url: ''
alertmanager_hipchat_api_url: ''
alertmanager_hipchat_auth_token: ''
alertmanager_wechat_url: ''
alertmanager_wechat_secret: ''
alertmanager_wechat_corp_id: ''

# First read: https://github.com/prometheus/alertmanager#high-availability
alertmanager_cluster:
  listen-address: ""
# alertmanager_cluster:
#   listen-address: "{{ ansible_default_ipv4.address }}:6783"
#   peers:
#     - "{{ ansible_default_ipv4.address }}:6783"
#     - "demo.cloudalchemy.org:6783"

# alertmanager_receivers: []
alertmanager_receivers:
  - name: slack
    slack_configs:
      - send_resolved: true
        channel: '#it'
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        # title: '{{ template "slack.title" . }}'
        # text: '{% raw %}{{ template "slack.text" . }}{% endraw %}'
        title: '{% raw %}{{ template "slack.monzo.title" . }}{% endraw %}'
        icon_emoji: '{% raw %}{{ template "slack.monzo.icon_emoji" . }}{% endraw %}'
        color: '{% raw %}{{ template "slack.monzo.color" . }}{% endraw %}'
        text: '{% raw %}{{ template "slack.monzo.text" . }}{% endraw %}'
        actions:
        - type: button
          text: 'Runbook :green_book:'
          url: '{% raw %}{{ (index .Alerts 0).Annotations.runbook }}{% endraw %}'
        - type: button
          text: 'Query :mag:'
          url: '{% raw %}{{ (index .Alerts 0).GeneratorURL }}{% endraw %}'
        - type: button
          text: 'Dashboard :grafana:'
          url: '{% raw %}{{ (index .Alerts 0).Annotations.dashboard }}{% endraw %}'
        - type: button
          text: 'Silence :no_bell:'
          url: '{% raw %}{{ template "__alert_silence_link" . }}{% endraw %}'
        - type: button
          text: '{% raw %}{{ template "slack.monzo.link_button_text" . }}{% endraw %}'
          url: '{% raw %}{{ .CommonAnnotations.link_url }}{% endraw %}'

alertmanager_inhibit_rules: []
# alertmanager_inhibit_rules:
#   - target_match:
#       label: value
#     source_match:
#       label: value
#     equal: ['dc', 'rack']
#   - target_match_re:
#       label: value1|value2
#     source_match_re:
#       label: value3|value5

# alertmanager_route: {}
alertmanager_route:
  repeat_interval: 1h
  receiver: slack
#   # This routes performs a regular expression match on alert labels to
#   # catch alerts that are related to a list of services.
#     - match_re:
#         service: ^(foo1|foo2|baz)$
#       receiver: team-X-mails
#       # The service has a sub-route for critical alerts, any alerts
#       # that do not match, i.e. severity != critical, fall-back to the
#       # parent node and are sent to 'team-X-mails'
#       routes:
#         - match:
#             severity: critical
#           receiver: team-X-pager
#     - match:
#         service: files
#       receiver: team-Y-mails
#       routes:
#         - match:
#             severity: critical
#           receiver: team-Y-pager
#     # This route handles all alerts coming from a database service. If there's
#     # no team to handle it, it defaults to the DB team.
#     - match:
#         service: database
#       receiver: team-DB-pager
#       # Also group alerts by affected database.
#       group_by: [alertname, cluster, database]
#       routes:
#         - match:
#             owner: team-X
#           receiver: team-X-pager
#         - match:
#             owner: team-Y
#           receiver: team-Y-pager

# The template for amtool's configuration
alertmanager_amtool_config_file: 'amtool.yml.j2'

# Location (URL) of the alertmanager
alertmanager_amtool_config_alertmanager_url: "{{ alertmanager_web_external_url }}"

# Extended output of `amtool` commands, use '' for less verbosity
alertmanager_amtool_config_output: 'extended'

```

* Ansible playbook execution Logs:

```
fatal: [10.10.10.151]: FAILED! => {"changed": false, "checksum": "ac7b62613e1c55fb5592a36f500c9fb6399e8cb0", "exit_status": 1, "msg": "failed to validate", "stderr": "amtool: error: failed to validate 1 file(s)\n\n", "stderr_lines": ["amtool: error: failed to validate 1 file(s)", ""], "stdout": "Checking '/root/.ansible/tmp/ansible-tmp-1601894343.1803482-191455237155978/source'  SUCCESS\nFound:\n - global config\n - route\n - 0 inhibit rules\n - 1 receivers\n - 1 templates\n  FAILED: template: slack.tmpl:14: unexpected EOF\n\n", "stdout_lines": ["Checking '/root/.ansible/tmp/ansible-tmp-1601894343.1803482-191455237155978/source'  SUCCESS", "Found:", " - global config", " - route", " - 0 inhibit rules", " - 1 receivers", " - 1 templates", "  FAILED: template: slack.tmpl:14: unexpected EOF", ""]}
```

**Anything else we need to know?**:
This is my slack.tmpl template
```
# This builds the silence URL.  We exclude the alertname in the range
# to avoid the issue of having trailing comma separator (%2C) at the end
# of the generated URL
{{ define "__alert_silence_link" -}}
    {{ .ExternalURL }}/#/silences/new?filter=%7B
    {{- range .CommonLabels.SortedPairs -}}
        {{- if ne .Name "alertname" -}}
            {{- .Name }}%3D"{{- .Value -}}"%2C%20
        {{- end -}}
    {{- end -}}
    alertname%3D"{{ .CommonLabels.alertname }}"%7D
{{- end }}



{{ define "__alert_severity_prefix" -}}
    {{ if ne .Status "firing" -}}
    :lgtm:
    {{- else if eq .Labels.severity "critical" -}}
    :fire:
    {{- else if eq .Labels.severity "warning" -}}
    :warning:
    {{- else -}}
    :question:
    {{- end }}
{{- end }}

{{ define "__alert_severity_prefix_title" -}}
    {{ if ne .Status "firing" -}}
    :lgtm:
    {{- else if eq .CommonLabels.severity "critical" -}}
    :fire:
    {{- else if eq .CommonLabels.severity "warning" -}}
    :warning:
    {{- else if eq .CommonLabels.severity "info" -}}
    :information_source:
    {{- else -}}
    :question:
    {{- end }}
{{- end }}


{{/* First line of Slack alerts */}}
{{ define "slack.monzo.title" -}}
    [{{ .Status | toUpper -}}
    {{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{- end -}}
    ] {{ template "__alert_severity_prefix_title" . }} {{ .CommonLabels.alertname }}
{{- end }}


{{/* Color of Slack attachment (appears as line next to alert )*/}}
{{ define "slack.monzo.color" -}}
    {{ if eq .Status "firing" -}}
        {{ if eq .CommonLabels.severity "warning" -}}
            warning
        {{- else if eq .CommonLabels.severity "critical" -}}
            danger
        {{- else -}}
            #439FE0
        {{- end -}}
    {{ else -}}
    good
    {{- end }}
{{- end }}


{{/* Emoji to display as user icon (custom emoji supported!) */}}
{{ define "slack.monzo.icon_emoji" }}:prometheus:{{ end }}

{{/* The test to display in the alert */}}
{{ define "slack.monzo.text" -}}
    {{ range .Alerts }}
        {{- if .Annotations.message }}
            {{ .Annotations.message }}
        {{- end }}
        {{- if .Annotations.description }}
            {{ .Annotations.description }}
        {{- end }}
    {{- end }}
{{- end }}



{{- /* If none of the below matches, send to #monitoring-no-owner, and we 
can then assign the expected code_owner to the alert or map the code_owner
to the correct channel */ -}}
{{ define "__get_channel_for_code_owner" -}}
    {{- if eq . "platform-team" -}}
        platform-alerts
    {{- else if eq . "security-team" -}}
        security-alerts
    {{- else -}}
        monitoring-no-owner
    {{- end -}}
{{- end }}

{{- /* Select the channel based on the code_owner. We only expect to get
into this template function if the code_owners label is present on an alert.
This is to defend against us accidentally breaking the routing logic. */ -}}
{{ define "slack.monzo.code_owner_channel" -}}
    {{- if .CommonLabels.code_owner }}
        {{ template "__get_channel_for_code_owner" .CommonLabels.code_owner }}
    {{- else -}}
        monitoring
    {{- end }}
{{- end }}

{{ define "slack.monzo.link_button_text" -}}
    {{- if .CommonAnnotations.link_text -}}
        {{- .CommonAnnotations.link_text -}}
    {{- else -}}
        Link
    {{- end }} :link:
{{- end }}
```
