### ISSUE TITLE
Unable to get the checksum due to errors in the Ansible

### ISSUE THREAD

**Issue by cgkades** [cloudalchemy/ansible-alertmanager#161]
https://github.com/cloudalchemy/ansible-alertmanager/blob/e42e7ef1f551fe3ae018f0b8400a62e733189206/tasks/preflight.yml#L44
Mac OS 10.14.6 ssh into Linux CentOS Linux release 7.9.2009

Ansible Version
```
ansible [core 2.11.4]
  config file = None
  configured module search path = ['/Users/yoakum/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/yoakum/venv/ansible/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/yoakum/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/yoakum/venv/ansible/bin/ansible
  python version = 3.9.6 (default, Jun 29 2021, 04:45:03) [Clang 11.0.0 (clang-1100.0.33.17)]
  jinja version = 2.11.2
  libyaml = True
```
Errors:
```
TASK [alertmanager : Get checksum for amd64 architecture] **********************************************************************************************************************************************************************************************************************
fatal: [3.239.126.164]: FAILED! => {"msg": "template error while templating string: expected token 'end of print statement', got 'select'. String: {{ lookup('url', 'https://github.com/prometheus/alertmanager/releases/download/v' + alertmanager_version + '/sha256sums.txt',
 wantlist=True) | list select('contains', 'linux-' + go_arch + '.tar.gz') | list | first).split(' ')[0] }}"}
...ignoring

TASK [alertmanager : Checksum lookup error message] ****************************************************************************************************************************************************************************************************************************
fatal: [3.239.126.164]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'alertmanager_checksum_url' is undefined\n\nThe error appears to be in '/Users/yoakum/git/analytics-techops/analytics-bakery/ansible/roles/alertmanager/tasks
/preflight.yml': line 51, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Checksum lookup error message\n  ^ here\n"}

PLAY RECAP *********************************************************************************************************************************************************************************************************************************************************************
3.239.126.164              : ok=5    changed=0    unreachable=0    failed=1    skipped=2    rescued=0    ignored=1
```

I was able to get passed part of this issue by adding a '(' before the lookup and then adding a '|' after list. I also had to add the checksum url to the main ansible because it was not being set.

```
"{{ (lookup('url', 'https://github.com/prometheus/alertmanager/releases/download/v' + alertmanager_version + '/sha256sums.txt', wantlist=True) | list | select('contains', 'linux-' + go_arch + '.tar.gz') | list | first).split(' ')[0] }}"
```

**Comment by cgkades** [comment]
Actually... there is a lot broken in that section (latest tag didn't work either). Here's what I had to have to get it to work with latest or a specified version 
```
- block:
    - name: Get latest release
      uri:
        url: "https://api.github.com/repos/prometheus/alertmanager/releases/latest"
        method: GET
        return_content: true
        status_code: 200
        body_format: json
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
      no_log: "{{ not lookup('env', 'MOLECULE_DEBUG') | bool }}"
      register: _latest_release
      until: _latest_release.status == 200
      retries: 5

    - name: "Set alertmanager version to {{ _latest_release.json.tag_name[1:] }}"
      set_fact:
        alertmanager_version: "{{ _latest_release.json.tag_name[1:] }}"
        alertmanager_checksum_url: "https://github.com/prometheus/alertmanager/releases/download/v{{ _latest_release.json.tag_name[1:] }}/sha256sums.txt"
  when:
    - alertmanager_version == "latest"
    - alertmanager_binary_local_dir | length == 0

- name: "Get checksum for {{ go_arch }} architecture"
  set_fact:
    alertmanager_checksum_url: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/sha256sums.txt"
    alertmanager_checksum: "{{ (lookup('url', 'https://github.com/prometheus/alertmanager/releases/download/v' + alertmanager_version + '/sha256sums.txt', wantlist=True) | list | select('contains', 'linux-' + go_arch + '.tar.gz') | list | first).split(' ')[0] }}"
  when:
    - alertmanager_binary_local_dir | length == 0
  ignore_errors: true
  register: alertmanager_checksum_lookup
```
