### ISSUE TITLE
Configure for Telegram

### ISSUE THREAD

**Issue by rmalenko** [cloudalchemy/ansible-alertmanager#170]
Hello,
It looks like this role can't use with Telegram just out of the box. Isn't yes?

**Comment by diraol** [comment]
Yeah, I'm facing issues too with the `cannot unmarshal !!str `<chat_id>` into int64", ""` error

**Comment by rmalenko** [comment]
I have found the solution which works for me. But I haven't tested yet if a message send 
```yaml
...
receivers:
- name: 'telegram'
  telegram_configs:
  - api_url: "https://api.telegram.org"
    bot_token: AAkO......VlM
    chat_id: -123456767...
    disable_notifications: false
    http_config:
      follow_redirects: true
    send_resolved: true
    parse_mode: MarkdownV2
...
```

**Comment by rlex** [comment]
simple example to send everything to telegram: 
```
alertmanager_receivers:
- name: telegram-receiver
  telegram_configs:
    - send_resolved: true
      http_config:
        follow_redirects: true
      api_url: https://api.telegram.org
      bot_token: YOUR_BOT_TOKEN
      chat_id: YOUR_CHAT_ID
      parse_mode: HTML
      message: '{% raw %}{{ template "telegram.default.message" .}}{% endraw %}'
alertmanager_route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 24h
  receiver: telegram-receiver
```
