### ISSUE TITLE
Problem with alertmanager_child_routes

### ISSUE THREAD

**Issue by kozicpetar** [cloudalchemy/ansible-alertmanager#98]
Hi,
if I put this route per severity which I using in cluster:

```
alertmanager_child_routes:
    - match:
        severity: Lowest
      receiver: slack

   - match:
       severity: Low
     receiver: jira
     continue: true
   - match:
       severity: Low
     receiver: slack

   - match:
        severity: High
     receiver: jira
     continue: true
   - match:
         severity: High
     receiver: slack
```

In alertmanager.yml I get:

```
routes:
  - match:
      severity: Lowest
    receiver: slack
  - continue: true
    match:
      severity: Low
    receiver: jira
  - match:
      severity: Low
    receiver: slack
  - continue: true
    match:
      severity: High
    receiver: jira
  - match:
      severity: High
    receiver: slack
  - continue: true
```

Expected:
```
- match:
    severity: Lowest
  receiver: slack

- match:
    severity: Low
  receiver: jira
  continue: true
- match:
    severity: Low
  receiver: slack

- match:
    severity: High
  receiver: jira
  continue: true
- match:
    severity: High
  receiver: slack
```

**Comment by paulfantom** [comment]
I don't see what is different here apart from different ordering for YAML maps (which is completely expected and correctly handled by ansible) and additional `- continue: true` which I have no idea where came from.

**Comment by kozicpetar** [comment]
@paulfantom different ordering is ok, I know that.
But continue:true need to be in the same ident as a receiver.
Continue is from documentation and I using continue in my configuration but I don't know why it isn't in the same ident.

**Comment by paulfantom** [comment]
You didn't specify it with the same indent. From what you supplied I see following:
```
alertmanager_child_routes:
    - match:
        severity: Lowest
      receiver: slack

   - match:
       severity: Low
     receiver: jira
     continue: true
```
With result as 
```
routes:
  - match:
      severity: Lowest
    receiver: slack
  - continue: true
    match:
      severity: Low
    receiver: jira
```

As you can see this is semantically identical. Maybe if you could supply the whole `route:` section, then it would be easier to debug.
