### ISSUE TITLE
Add a real life example playbook

### ISSUE THREAD

**Issue by rgarrigue** [cloudalchemy/ansible-alertmanager#99]
Hi

Please add a real life example playbook. An "empty" one just including role isn't enought, as the assert enforce you need receiver & route. And coming up with the proper yaml is a bit tedious. Just something like this would have helped getting stuff really started

```yaml
---
# https://github.com/cloudalchemy/ansible-alertmanager

alertmanager_web_external_url: alertmanager.domain.tld

alertmanager_receivers:
  - name: infra-ml
    email_configs:
      - to: "infra@domain.tld"
        from: "monitoring@domain.tld"
        smarthost: "smtp.gmail.com:587"
        auth_username: "monitoring@domain.tld"
        auth_identity: "monitoring@domain.tld"
        auth_password: UseGmailAppToken

alertmanager_route:
  group_by: ["..."]
  receiver: infra-ml
```

Best regards,
